### ISSUE TITLE
Pull down dependency files from melpa or marmalade.

### ISSUE THREAD

**Issue by jaseemabid** [ghoseb/dotemacs#22]
Is there a  specific reason why you don't use the built in package manager? Keeping track of upstream elisp packages is just impossible (I have ~70). The obvious downside is that you cannot lock to a specific version of a package, but I think its an overall elegant way of doing things. Common approach is to define a meta package with all your required packages as dependencies, or just maintaining a list of packages that needs to be installed and installing them all on boot. 

PS: I was just reading through the dotemacs because of the obvious difference in the way it's structured.

**Comment by ghoseb** [comment]
I use Cask now. It uses the built-in package manager.
