### ISSUE TITLE
Error on initialization

### ISSUE THREAD

**Issue by alolis** [ghoseb/dotemacs#4]
Hello,

I've downloaded dotemacs, extracted the contents to my ~/.emacs.d folder, started emacs and i am getting the following error:

```
 Warning (initialization): An error occurred while loading `/home/tester/.emacs.d/init.el':

 Wrong number of arguments: #[(theme) \211    >)\203
```

Any ideas?

**Comment by ghoseb** [comment]
You should be on Emacs 24 to be able to use my config. Can you please confirm your Emacs version?

**Comment by alolis** [comment]
Thanks for your reply. I am on Emacs 23, I will give it a go with 24 and get back to you

**Comment by alolis** [comment]
Well, now the theme is loading but i am seeing a different error:

```
error: Font not available #<font-spec nil nil Anonymous Pro nil nil nil nil 14.0 nil nil nil ((:name . Anonymous Pro-  14)         (user-spec . Anonymous Pro-14))>
```

I am on Ubuntu 11.10 by the way and i had to install emacs-snapshot to get 24 since the latest one is 23 on the repository.

**Comment by alolis** [comment]
Well, i just had to install the Anonymous Pro font. Apparently it's not installed by default in Ubuntu.

**Comment by ghoseb** [comment]
Yeah, or you could have just changed that line to use a system default font, like "DejaVu Sans Mono".

**Comment by alolis** [comment]
Thanks for the info :) Kinda new to emacs world heh.

**Comment by ghoseb** [comment]
No problem, let me know if you face any other issues.
